Flutre/#7-question-model
bens-schreiber/CPTS-322-Course-Project pull request #13
Opened 2024-04-25 00:15 UTC by DamiennFl

fixes #7 

Question Model created, with an ID, text, and a session which it is connected to.

2024-04-25 00:27 UTC, bens-schreiber requested changes

2024-04-25 00:27 UTC, bens-schreiber commented on backend/pollpall_project/session/models.py
> +    questionID = models.IntegerField(primary_key=True)
nit: lets name this question_id

2024-04-25 00:27 UTC, bens-schreiber commented on backend/pollpall_project/session/models.py
> +    question_text = models.CharField(max_length=255)
question_text should just be called prompt, and it can be a lot bigger than 255, lets go for 0xFFF

2024-04-25 00:27 UTC, bens-schreiber commented on backend/pollpall_project/session/tests.py
> +class TestQuestionModel(TestCase):
We don't really need any tests on just the model, since it doesn't really do anything other than just be a model. We will test the Views though

2024-04-25 00:29 UTC, bens-schreiber commented on backend/pollpall_project/session/tests.py
> +    def test_question_str_method(self):
When we do actually do tests, remember to follow Arrange Act Assert, and use comments `
// Arrange
... code

// Act
... code

// Assert
... code
`

2024-04-25 00:36 UTC, bens-schreiber commented
We should create an answer model with a one to many relationship with Question

2024-04-26 18:33 UTC, DamiennFl commented
@bens-schreiber one to many connection is handled automatically by foreignKey. Dillon changed the code to remove circular imports, but it should work as intended.

2024-04-26 18:42 UTC, bens-schreiber commented on backend/pollpall_project/session/migrations/0002_question.py
> +class Migration(migrations.Migration):
Looks like you haven't migrated the db yet. Remove this migration, and then make a  migration with the new changes. Migrations are important to understand: https://docs.djangoproject.com/en/5.0/topics/migrations/

2024-04-26 18:44 UTC, bens-schreiber commented on backend/pollpall_project/session/models.py
> +    session = models.ForeignKey('Session', on_delete=models.CASCADE)
nit: 
```suggestion
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
```'

use the object Session and not a string

2024-04-26 18:44 UTC, bens-schreiber commented on backend/pollpall_project/session/models.py
> +    related_poll = models.ForeignKey('Poll', on_delete=models.CASCADE, related_name='related_questions') # If poll is deleted, also delete question from database.
```suggestion
    related_poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='related_questions') # If poll is deleted, also delete question from database.
```

2024-04-26 18:45 UTC, bens-schreiber commented on backend/pollpall_project/session/models.py
> +    question = models.ForeignKey('Question', on_delete=models.CASCADE) # Connects Response to Question.
```suggestion
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # Connects Response to Question.
```

2024-04-26 18:50 UTC, bens-schreiber commented on backend/pollpall_project/session/models.py
> +class Question(models.Model): # Just holds a question ID and the question
In python, we can use Docustrings for documentation
```suggestion
class Question(models.Model):
""" 

Holds the question we are asking 

    Attributes:
        question_id (int): The primary key of the model
        prompt (str): The question we are asking
        poll (Poll): The poll this question comes from
"""
```

2024-04-26 18:53 UTC, bens-schreiber approved these changes
LGTM

2024-04-26 20:18 UTC, merged